using System;
using System.Collections.Generic;
using System.IO;
using ClaudeCodeMCP.Editor.DevSetup.Util;
using UnityEditor;
using UnityEngine;

namespace ClaudeCodeMCP.Editor.DevSetup.Installers
{
    /// <summary>
    /// Microsoft.Unity.Analyzers と Roslynator.Analyzers を NuGet から取得し、
    /// Assets/Plugins/ClaudeCodeMCP_DevSetup/Analyzers/ 配下に配置して
    /// Roslyn アナライザーとして登録する。
    /// </summary>
    internal static class AnalyzerInstaller
    {
        public const string MicrosoftUnityAnalyzersId = "Microsoft.Unity.Analyzers";
        public const string MicrosoftUnityAnalyzersVersion = "1.23.0";

        public const string RoslynatorAnalyzersId = "Roslynator.Analyzers";
        public const string RoslynatorAnalyzersVersion = "4.12.9";

        public const string GlobalConfigFileName = "ClaudeCodeMCP.DevSetup.Analyzers.globalconfig";

        public static string TargetDirectoryAbsolute
        {
            get { return Path.Combine(ProjectPaths.DevSetupAssetsRoot, "Analyzers"); }
        }

        public static string TargetDirectoryRelative
        {
            get { return "Assets/Plugins/ClaudeCodeMCP_DevSetup/Analyzers"; }
        }

        public static bool IsInstalled()
        {
            string dir = TargetDirectoryAbsolute;
            if (!Directory.Exists(dir)) return false;
            string[] dlls = Directory.GetFiles(dir, "*.dll", SearchOption.TopDirectoryOnly);
            return dlls.Length > 0;
        }

        public static void Install(out string summary)
        {
            List<string> messages = new List<string>();
            string dir = TargetDirectoryAbsolute;
            Directory.CreateDirectory(dir);

            try
            {
                List<string> unityDlls = NuGetPackageFetcher.DownloadAndExtractAnalyzers(
                    MicrosoftUnityAnalyzersId, MicrosoftUnityAnalyzersVersion, dir);
                messages.Add(string.Format("{0} {1}: extracted {2} dll(s)",
                    MicrosoftUnityAnalyzersId, MicrosoftUnityAnalyzersVersion, unityDlls.Count));
            }
            catch (Exception ex)
            {
                messages.Add(string.Format("{0} fetch failed: {1}", MicrosoftUnityAnalyzersId, ex.Message));
            }

            try
            {
                List<string> roslynatorDlls = NuGetPackageFetcher.DownloadAndExtractAnalyzers(
                    RoslynatorAnalyzersId, RoslynatorAnalyzersVersion, dir);
                messages.Add(string.Format("{0} {1}: extracted {2} dll(s)",
                    RoslynatorAnalyzersId, RoslynatorAnalyzersVersion, roslynatorDlls.Count));
            }
            catch (Exception ex)
            {
                messages.Add(string.Format("{0} fetch failed: {1}", RoslynatorAnalyzersId, ex.Message));
            }

            WriteGlobalConfig(dir);
            messages.Add("globalconfig written");

            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
            ConfigureAllDllsAsAnalyzers(dir);

            summary = string.Join("\n", messages);
        }

        public static void Uninstall(out string summary)
        {
            string dir = TargetDirectoryAbsolute;
            if (!Directory.Exists(dir))
            {
                summary = "Analyzer directory does not exist; nothing to remove.";
                return;
            }
            try
            {
                Directory.Delete(dir, true);
                string meta = dir + ".meta";
                if (File.Exists(meta)) File.Delete(meta);
                AssetDatabase.Refresh();
                summary = "Removed " + dir;
            }
            catch (Exception ex)
            {
                summary = "Failed to remove: " + ex.Message;
            }
        }

        private static void WriteGlobalConfig(string analyzerDir)
        {
            string body =
                "# Auto-generated by ClaudeCodeMCP DevSetup. Customize freely; not overwritten on reinstall if present.\n" +
                "is_global = true\n\n" +
                "# === Microsoft.Unity.Analyzers (UNT****) ===\n" +
                "dotnet_diagnostic.UNT0001.severity = warning   # Empty Unity message\n" +
                "dotnet_diagnostic.UNT0002.severity = warning   # Inefficient tag comparison\n" +
                "dotnet_diagnostic.UNT0003.severity = warning   # Generic GetComponent\n" +
                "dotnet_diagnostic.UNT0004.severity = warning   # Time.fixedDeltaTime in Update\n" +
                "dotnet_diagnostic.UNT0005.severity = warning   # Time.deltaTime in FixedUpdate\n" +
                "dotnet_diagnostic.UNT0008.severity = warning   # Null propagation on UnityEngine.Object\n" +
                "dotnet_diagnostic.UNT0014.severity = warning   # GetComponent type constraint\n" +
                "dotnet_diagnostic.UNT0023.severity = none      # Coalescing assignment on UE.Object (false positive cases)\n\n" +
                "# === Roslynator (RCS****) ===\n" +
                "dotnet_analyzer_diagnostic.category-Roslynator.severity = suggestion\n";

            string path = Path.Combine(analyzerDir, GlobalConfigFileName);
            if (!File.Exists(path))
            {
                File.WriteAllText(path, body);
            }
        }

        private static void ConfigureAllDllsAsAnalyzers(string analyzerDir)
        {
            string[] dlls = Directory.GetFiles(analyzerDir, "*.dll", SearchOption.TopDirectoryOnly);
            foreach (string absDllPath in dlls)
            {
                string assetPath = ToAssetRelativePath(absDllPath);
                if (string.IsNullOrEmpty(assetPath)) continue;
                AssetDatabase.ImportAsset(assetPath, ImportAssetOptions.ForceSynchronousImport);

                PluginImporter importer = AssetImporter.GetAtPath(assetPath) as PluginImporter;
                if (importer == null) continue;

                importer.SetCompatibleWithAnyPlatform(false);
                importer.SetCompatibleWithEditor(false);

                UnityEngine.Object obj = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(assetPath);
                if (obj != null)
                {
                    AssetDatabase.SetLabels(obj, new[] { "RoslynAnalyzer" });
                }

                EditorUtility.SetDirty(importer);
                importer.SaveAndReimport();
            }
        }

        private static string ToAssetRelativePath(string absolutePath)
        {
            string normAbs = absolutePath.Replace('\\', '/');
            string normRoot = ProjectPaths.AssetsRoot.Replace('\\', '/');
            if (!normAbs.StartsWith(normRoot, StringComparison.OrdinalIgnoreCase)) return null;
            return "Assets" + normAbs.Substring(normRoot.Length);
        }
    }
}
